all:
    make -fc64_bfp3_kfp.mak

clear:
    del  *.asm
    del  *.pp
    del  *.obj
    del  *.~*
    del  *.bak
    del  *.tds
    del  *.lkf
    del  *.log
    del  *.map
    del  *.paf2
    del  *.sbl
    del  *.tmp
    del  .\Release\*.*
